version: "3"
networks:
  selenium-grid-network:
    driver: bridge
    name: selenium-grid-network  # Explicit network name

services:
  selenium-hub:
    image: selenium/hub:4.27.0  # Use a specific version of Selenium Hub
    container_name: selenium-hub
    ports:
      - "4445:4444"  # Map port 4444 in the container to 4445 on the host
    #environment:
      #- GRID_MAX_SESSION=5  # Maximum parallel sessions
      #- SE_OPTS=--log-level INFO --relax-checks true  # Additional configurations
    networks:
      - selenium-grid-network

  chrome:
    image: selenium/node-chrome:4.27.0  # Use a specific version of Chrome Node
    #container_name: chrome-node
    ports:
      - "5900"  # VNC port for debugging
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-grid-network

  firefox:
    image: selenium/node-firefox:4.27.0  # Use a specific version of Firefox Node
    #container_name: firefox-node
    ports:
      - "5901"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-grid-network

  edge:
    image: selenium/node-edge:4.27.0  # Use a specific version of Edge Node
    #container_name: edge-node
    ports:
      - "5902"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-grid-network
